version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    groups:
      dependencies:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "automerge"